// TODO: ADD TRANSACTION
// TODO: DELETE TRANSACTION
// TODO: UPDATE TRANSACTION
// TODO: VIEW ALL TRANSACTOIN

// aggrigator functions
// TODO: TOTAL SPENDINGS
// TODO: TOTAL BALANCE
// TODO: TOTAL SPENDING PER DAY
// TODO: TOTAL SPENDING PER MONTH
// TODO: TOTAL SPENDING PER YEAR
